### ISSUE TITLE
Demo 中的支付出现错误

### ISSUE THREAD

**Issue by playniuniu** [shima-park/unionpay#1]
Hi

我在做 Golang 银联支付的项目，看到您这边的实现，觉得很不错

但是在使用 Demo 的时候，出现 交易失败 11[9100004]Signature verification failed 的错误

想请教一下，是什么原因

**Comment by shima-park** [comment]
? 我刚刚试了下我这个demo，还是可以成功支付的。
使用的项目下的证书及秘钥,以及测试的账号。

首先访问 http://localhost:9090/index 选择银联网页支付
输入测试的银行卡 6216261000000000018
测试的用户名:全渠道    身份证:341126197709218366
测试的验证码: 111111

**Comment by zangetsudo** [comment]
HI, 我这边测试，支付成功后，返回404 找不到网页，将demo中的返回路径修改为：
	returnURL = fmt.Sprintf("%s/%s", localTunnel, "unionpay/return")
	notifyURL = fmt.Sprintf("%s/%s", localTunnel, "unionpay/notify-web")
	//returnNotifyURL = fmt.Sprintf("%s/%s", localTunnel, "unionpay/return-notify")


出错：
Error:crypto/rsa: verification error

想请教一下，是什么原因？？

**Comment by shima-park** [comment]
@zangetsudo 感谢你的评论，上面这个问题我刚刚已经修过了提交了。Error:crypto/rsa: verification error 这个是因为银联这边证书更新。"全渠道加密与验签测试证书（最新）更新时间： 2017-11-29" https://open.unionpay.com/ajweb/help/file/techFile?productId=1
