### ISSUE TITLE
unknown key type "PRIVATE KEY", want "RSA PRIVATE KEY"

### ISSUE THREAD

**Issue by chengxiao** [shima-park/unionpay#2]
在使用 demo 代码跑成功了,但是尝试换成自己的测试 key 和 cert 中
使用代码中的方法

> openssl pkcs12 -in my.pfx -clcerts -nokeys -out key.cert

和

> openssl pkcs12 -in my.pfx -nocerts -nodes -out key.pem

然后在打码中使用会报

> unknown key type "PRIVATE KEY", want "RSA PRIVATE KEY"

**Comment by shima-park** [comment]
粗看感觉是生成的 key.pem不对, 你和我示例中的key.pem格式比较一下看,是否有区别.
